# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c9ec8b414affb96fe51b73b1441144f54b86e104107cea5ede0433ce03b0f08421d11e32b91986ab43ac2d0871fdc866a75f0e57cad9fb6d3eaa15577f90033

test:
  secret_key_base: fd4d4e823c4891aa1163f86dece5e633ec987c11526e7d201cf912e411875f507271d172a837bc6b92e48e53323a4bfb12ce015acc74a0c96581489ef758a633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
